version: '3'
services:
#  backend:
##    build: .
#    image: 'livedocker:latest'  # Defina o nome e a tag da imagem resultante da construção do Dockerfile
#    ports:
#      - "8080:8080"
##    environment:
##      - 'SPRING_PROFILES_ACTIVE=prod'  # Defina as variáveis de ambiente necessárias para a aplicação
##      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/zeroToDeploy
##      - SPRING_DATASOURCE_USERNAME=postgres
##      - SPRING_DATASOURCE_PASSWORD=postgres
##      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    depends_on:
#      - postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=zeroToDeploy'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
#  rabbitmq:
#    image: 'rabbitmq:latest'
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=secret'
#      - 'RABBITMQ_DEFAULT_USER=myuser'
#    ports:
#      - '5672'