CREATE TABLE IF NOT EXISTS customer (
   id UUID NOT NULL,
   code SERIAL NOT NULL,
   name VARCHAR(255) NOT NULL,
   age INTEGER NOT NULL,
   active BOOLEAN DEFAULT TRUE,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_customer PRIMARY KEY (id)
);